services:
  - type: web
    name: askroom
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: askroom-db
          property: connectionString
      - key: VITE_ADMIN_ACCOUNT
        sync: false
      - key: VITE_ADMIN_PASSWORD
        sync: false

databases:
  - name: askroom-db
    databaseName: askroom
    user: askroom
