services:
  - type: web
    name: askroom
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_ADMIN_ACCOUNT
        sync: false
      - key: VITE_ADMIN_PASSWORD
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
